### PR TITLE
Allow setting a selection condition for the entry chooser in settings

### PR DESCRIPTION
**Pull request by Numkil**
Implements #7

### CODE REVIEW

**Review by HannahDeWachter — COMMENTED** [review]
@Numkil Seems to work great! 
Only one suggestion: maybe the setting should be placed in the Entry tab instead of the General settings of the field. 
Screenshot 2023-09-13 at 08 54 39

**Comment by Numkil** [comment]
@HannahDeWachter 

Yes that is a much more logical place to put it!

I moved the position of the setting to the Entry tab and it works fine :) 

If you are happy with it we can merge!

**Comment by janhenckens** [comment]
Would it make sense to have a similar condition for assets or categories? If possible of course.

**Comment by Numkil** [comment]
Its definitely possible to implement but it will require a bit of refactoring as we will need to save all the selectionconditions seperately per ElementLinkType. 

Maybe this could be a seperate PR to extend the condition to assets and categories so that we can already start using this as a basic functionality

**Comment by janhenckens** [comment]
@Numkil Sounds good and indeed not a big priority for now.

**Pull request merged**
